# version: '4.26'
# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Password123
#       - MSSQL_PID=Express
#     ports:
#       - 1433:1433
#     volumes:
#       - ./data:/var/opt/mssql/data

version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
